[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
signal_clash_vault = "7fgxvrdpcYMhqLZP9E1mFDQFmffE7ifALVdUm8owG5Lv"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
